-- Forma / CV Personalizer schema for Supabase Postgres.
-- Paste this entire file into Supabase Dashboard > SQL Editor and click Run.
-- It is idempotent, so it is safe to run again after pulling an update.

create table if not exists public.resume_versions (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    data text not null,
    template_id text not null default 'modern',
    created_at timestamptz not null default now(),
    is_current boolean not null default false,
    constraint resume_versions_template_id_check check (
        template_id in ('modern', 'classic', 'minimal', 'executive', 'creative', 'technical')
    )
);

create table if not exists public.job_applications (
    id bigint generated by default as identity primary key,
    company text not null,
    position text not null,
    url text,
    status text not null default 'applied',
    resume_version_id bigint references public.resume_versions(id) on delete set null,
    applied_at timestamptz not null default now(),
    notes text,
    updated_at timestamptz
);

create table if not exists public.cover_letters (
    id bigint generated by default as identity primary key,
    resume_version_id bigint not null references public.resume_versions(id) on delete cascade,
    company text not null,
    position text not null,
    source_url text,
    job_post text not null,
    content text not null,
    generation_context text,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

create table if not exists public.company_research_reports (
    id bigint generated by default as identity primary key,
    company text not null,
    website_url text,
    role text,
    job_context text,
    focus text,
    report text not null,
    researched_at text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.profile_assets (
    id text primary key,
    content_type text not null,
    data bytea not null,
    updated_at timestamptz not null default now()
);

alter table public.resume_versions
    add column if not exists template_id text not null default 'modern';
alter table public.cover_letters
    add column if not exists generation_context text;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'resume_versions_template_id_check'
          and conrelid = 'public.resume_versions'::regclass
    ) then
        alter table public.resume_versions
            add constraint resume_versions_template_id_check check (
                template_id in ('modern', 'classic', 'minimal', 'executive', 'creative', 'technical')
            );
    end if;
end $$;

create index if not exists idx_company_research_created
    on public.company_research_reports (created_at desc, id desc);
create index if not exists idx_company_research_company
    on public.company_research_reports (lower(company));
create index if not exists idx_jobs_resume_version
    on public.job_applications (resume_version_id);
create index if not exists idx_cover_letters_resume_version
    on public.cover_letters (resume_version_id);

-- Forma talks to Postgres only from its trusted backend. Browser-facing
-- Supabase roles get no table privileges; the database connection remains secret.
alter table public.resume_versions enable row level security;
alter table public.job_applications enable row level security;
alter table public.cover_letters enable row level security;
alter table public.company_research_reports enable row level security;
alter table public.profile_assets enable row level security;

revoke all on table public.resume_versions from anon, authenticated, service_role;
revoke all on table public.job_applications from anon, authenticated, service_role;
revoke all on table public.cover_letters from anon, authenticated, service_role;
revoke all on table public.company_research_reports from anon, authenticated, service_role;
revoke all on table public.profile_assets from anon, authenticated, service_role;
revoke all on sequence public.resume_versions_id_seq from anon, authenticated, service_role;
revoke all on sequence public.job_applications_id_seq from anon, authenticated, service_role;
revoke all on sequence public.cover_letters_id_seq from anon, authenticated, service_role;
revoke all on sequence public.company_research_reports_id_seq from anon, authenticated, service_role;

-- Keep future objects private by default. Forma does not use the Data API.
alter default privileges for role postgres in schema public
    revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
    revoke execute on functions from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
    revoke usage, select on sequences from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
    revoke execute on functions from public;
